// Explicit publish allowlist: source paths relative to the repository root.
export const frontendAssets = [
  ["work/assets/films/your-property-23s.mp4", "assets/films/your-property-23s.mp4"],
  ["work/assets/films/your-property-23s-start.webp", "assets/films/your-property-23s-start.webp"],
  ["work/assets/films/your-property-23s-end.webp", "assets/films/your-property-23s-end.webp"],
  ["work/preacherman-entry.js", "preacherman-entry.js"],
  ["work/preacherman-entry.css", "preacherman-entry.css"],
  ["work/assets/films/state-engine-24s.mp4", "assets/films/state-engine-24s.mp4"],
  ["work/assets/films/state-engine-24s-start.webp", "assets/films/state-engine-24s-start.webp"],
  ["work/assets/films/state-engine-24s-end.webp", "assets/films/state-engine-24s-end.webp"],
  ["work/preacherman-films.js", "preacherman-films.js"],
  ["work/preacherman-films.css", "preacherman-films.css"],
  ["work/assets/films/vessel-gallery-23s.mp4", "assets/films/vessel-gallery-23s.mp4"],
  ["work/assets/films/vessel-gallery-23s-start.webp", "assets/films/vessel-gallery-23s-start.webp"],
  ["work/assets/films/vessel-gallery-23s-end.webp", "assets/films/vessel-gallery-23s-end.webp"],
  ["work/assets/films/01-dark.mp4", "assets/films/01-dark.mp4"],
  ["work/assets/films/01-dark-start.webp", "assets/films/01-dark-start.webp"],
  ["work/assets/films/01-dark-end.webp", "assets/films/01-dark-end.webp"],
  ["work/assets/films/01-light.mp4", "assets/films/01-light.mp4"],
  ["work/assets/films/01-light-start.webp", "assets/films/01-light-start.webp"],
  ["work/assets/films/01-light-end.webp", "assets/films/01-light-end.webp"],
  ["work/assets/films/02-dark.mp4", "assets/films/02-dark.mp4"],
  ["work/assets/films/02-dark-start.webp", "assets/films/02-dark-start.webp"],
  ["work/assets/films/02-dark-end.webp", "assets/films/02-dark-end.webp"],
  ["work/assets/films/02-light.mp4", "assets/films/02-light.mp4"],
  ["work/assets/films/02-light-start.webp", "assets/films/02-light-start.webp"],
  ["work/assets/films/02-light-end.webp", "assets/films/02-light-end.webp"],
  ["work/assets/films/03-dark.mp4", "assets/films/03-dark.mp4"],
  ["work/assets/films/03-dark-start.webp", "assets/films/03-dark-start.webp"],
  ["work/assets/films/03-dark-end.webp", "assets/films/03-dark-end.webp"],
  ["work/assets/films/03-light.mp4", "assets/films/03-light.mp4"],
  ["work/assets/films/03-light-start.webp", "assets/films/03-light-start.webp"],
  ["work/assets/films/03-light-end.webp", "assets/films/03-light-end.webp"],
  ["work/assets/films/04-dark.mp4", "assets/films/04-dark.mp4"],
  ["work/assets/films/04-dark-start.webp", "assets/films/04-dark-start.webp"],
  ["work/assets/films/04-dark-end.webp", "assets/films/04-dark-end.webp"],
  ["work/assets/films/04-light.mp4", "assets/films/04-light.mp4"],
  ["work/assets/films/04-light-start.webp", "assets/films/04-light-start.webp"],
  ["work/assets/films/04-light-end.webp", "assets/films/04-light-end.webp"],

  ["work/Preacherman-Standalone.html", "index.html"],
  ["work/preacherman-hero.js", "preacherman-hero.js"],
  ["work/preacherman-profile.js", "preacherman-profile.js"],
  ["work/preacherman-profile.css", "preacherman-profile.css"],
  ["work/profile-capture.js", "profile-capture.js"],
  ["work/profile-lens.js", "profile-lens.js"],
  ["work/profile-shader.js", "profile-shader.js"],
  ["work/assets/profile/profile.woff2", "assets/profile/profile.woff2"],
  ["work/assets/pathfinder/pathfinder-poster.webp", "assets/pathfinder/pathfinder-poster.webp"],
  ["work/preacherman-hero.css", "preacherman-hero.css"],
  ["work/assets/pathfinder/pathfinder-runtime.glb", "assets/pathfinder/pathfinder-runtime.glb"],
  ["work/vendor/three-pathfinder-0.185.1.js", "vendor/three-pathfinder-0.185.1.js"],
  ["work/vendor/three-LICENSE.txt", "vendor/three-LICENSE.txt"],
  ["work/preacherman-auth.js", "preacherman-auth.js"],
  ["work/preacherman-auth-config.js", "preacherman-auth-config.js"],
  ["work/vendor/supabase-js-2.116.0.js", "vendor/supabase-js-2.116.0.js"],
  ["work/vendor/supabase-js-LICENSE.txt", "vendor/supabase-js-LICENSE.txt"],
];

export const authScriptPaths = [
  "/preacherman-auth-config.js",
  "/vendor/supabase-js-2.116.0.js",
  "/preacherman-auth.js",
];
